@startuml
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

' This is called C4 Component Diagram

LAYOUT_WITH_LEGEND()

title LSM storage architecture

skinparam sequence {
    ArrowColor Black
    ArrowFontColor Black
}

Person(user, "End user of the library")

Boundary(storage, "LSM Storage system") {

    System(inmem, "In-memory storage") {
        Component(memtable, "MemTable", "Golang", "Stores the in-memory small data snapshot")
    }

    System(persistent, "Persistent storage") {

        Boundary(commitlog_system, "CommitLog") {
            Component(commitlogManager, "CommitLog Manager", "Golang", "A system that manages current opened commitlog")
            ComponentDb(commitlogA, "CommitLog-A", "Golang + FS file", "Stores the unsorted log of the added data, in the order of appearance")
            ComponentDb(commitlogB, "CommitLog-B", "Golang + FS file", "A secondary commitlog used when the first one is being flushed on disk")
        }

        Boundary(sstable_system, "SSTable") {
            Component(sstable, "SSTable Manager", "Golang", "Stores the data on disk in separate files, one file per tag, having the key of timestamp")
            ComponentDb(dbfile1, "SSTableForTag", "Golang + FS file", "The data for the first tag")
            ComponentDb(dbfile2, "SSTableForTag", "Golang + FS file", "The data for the second tag")
            ComponentDb(dbfile3, "SSTable file ...", "Golang + FS file", "")
        }
    }

    Component(dbwriter, "DBWriter", "Golang", "Writes the commitlog to SSTables")
    Component(dbreader, "DBReader", "Golang", "Indexes the SSTables")

    Component(swriter, "StorageWriter", "Golang", "Contains the storage writing logic")
    Component(sreader, "StorageReader", "Golang", "Contains the storage reading logic")
}


Rel(sstable, dbfile1, "The data for the first tag")
Rel(sstable, dbfile2, "The data for the second tag")
Rel(sstable, dbfile3, "...")

Rel(commitlogManager, commitlogA, "Writes the data to")
Rel(commitlogManager, commitlogB, "Writes the data to")

Rel(dbwriter, commitlogManager, "Reads the commit log")
Rel(dbwriter, sstable, "Applies the commitlog data to SSTables")
Rel(dbreader, sstable, "Reads and indexes data from SSTables")

Rel(swriter, commitlogManager, "Sends the written data to commitlog")
Rel(swriter, memtable, "Sends the written data to MemTable")
Rel(swriter, dbwriter, "Triggers the SSTable merge")

Rel(sreader, memtable, "Retrieves the data from MemTable")
Rel(sreader, dbreader, "Retrieves the data from SSTables")

Rel(user, sreader, "Data retrieve requests")
Rel(user, swriter, "Data store requests")

@enduml